// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestowanieWebApi.Database;

#nullable disable

namespace TestowanieWebApi.Migrations
{
    [DbContext(typeof(ClientContext))]
    [Migration("20221102135140_migration3")]
    partial class migration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("TestowanieWebApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TestowanieWebApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShoppingHistoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingHistoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TestowanieWebApi.Models.ShoppingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientForeignKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientForeignKey")
                        .IsUnique();

                    b.ToTable("ShoppingHistory");
                });

            modelBuilder.Entity("TestowanieWebApi.Models.Product", b =>
                {
                    b.HasOne("TestowanieWebApi.Models.ShoppingHistory", null)
                        .WithMany("Products")
                        .HasForeignKey("ShoppingHistoryId");
                });

            modelBuilder.Entity("TestowanieWebApi.Models.ShoppingHistory", b =>
                {
                    b.HasOne("TestowanieWebApi.Models.Client", "Client")
                        .WithOne("ShoppingHistory")
                        .HasForeignKey("TestowanieWebApi.Models.ShoppingHistory", "ClientForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TestowanieWebApi.Models.Client", b =>
                {
                    b.Navigation("ShoppingHistory")
                        .IsRequired();
                });

            modelBuilder.Entity("TestowanieWebApi.Models.ShoppingHistory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
